[colors.primary]
background = "#282828"
foreground = "#eddbb2"

[[colors.indexed_colors]]
color = "#eddbb2"
index = 17

[colors.normal]
black = "#1d2021"
blue = "#83a598"
cyan = "#8ec07c"
green = "#b8bb26"
magenta = "#d3869b"
red = "#fb4934"
white = "#fbf1c7"
yellow = "#fabd2f"

[colors.bright]
black = "#1d2021"
blue = "#83a598"
cyan = "#8ec07c"
green = "#b8bb26"
magenta = "#d3869b"
red = "#fb4934"
white = "#fbf1c7"
yellow = "#fabd2f"

[colors.cursor]
cursor = "#fb4934"
text = "#282828"

[colors.hints.end]
background = "#fabd2f"
foreground = "#212429"

[colors.hints.start]
background = "#fabd2f"
foreground = "#212429"

[colors.line_indicator]
background = "None"
foreground = "None"

[colors.selection]
background = "#b8bb26"
text = "#1E1E2E"